namespace: aybarsm
name: utils
version: 1.0.0
readme: README.md
authors:
  - Murat Aybars <murat.aybars@blrm.co>
description: An opinionated custom Ansible utility collection
tags: [tools, infrastructure]
repository: https://github.com/aybarsm/ansible-collection-utils
