forbid_circular_dependencies = true

exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
    "**/dev",
    "**/*.bak*",
    "**/*.pyc",
]

source_roots = ["."]

[[modules]]
path = "ansible_collections.aybarsm.utils"
depends_on = []